apiVersion: v2
name: node-placeholder-scaler
description: A Helm chart for the JupyterHub Node Placeholder Calendar Scaler
type: application
version: 0.0.1-0.dev.git.296.h147bcb1
appVersion: "1.16.0"
