{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-placeholder-scaler.fullname" . }}
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["create", "get", "patch"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments/scale"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-placeholder-scaler.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-placeholder-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "node-placeholder-scaler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-placeholder-scaler.fullname" . }}-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-placeholder-scaler.fullname" . }}-node-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "node-placeholder-scaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "node-placeholder-scaler.fullname" . }}-node-reader
  apiGroup: rbac.authorization.k8s.io

{{- end }}